remote_theme: pages-themes/minimal@v0.2.0
title: Rui Fazendeiro | CAD & Systems Developer
description: >
  Electrical Systems & Software Engineering
  <br><br>
  🎓 BSc Student in Computer Engineering (UAb)
    <br><br>
  ⚡ Certified Electrotechnical Technician
  <br><br>
  🗣️ Portuguese (Native) | English (C1)
  <br><br>
  📍 Baião, Portugal
  <br><br>
  <a href="mailto:ruifazendeiro@outlook.pt">📩 Email</a> | 
  <a href="https://www.linkedin.com/in/rfazendeiro/">💼 LinkedIn</a> | 
  <a href="https://github.com/RuiFazendeiro">💻 GitHub</a>
  <br><br>
  📄 <a href="/assets/cv_rui_fazendeiro.pdf" target="_blank"><strong>Download CV (PDF)</strong></a>
plugins:
- jekyll-remote-theme
